### ISSUE TITLE
Test project no longer builds after update to xunit.visualstudio.runner v2.4.2

### ISSUE THREAD

**Issue by logiclrd** [xunit/visualstudio.xunit#218]
We have a test project that has been a part of our solution for several months and which is tested automatically during C.I. of every commit. After updating from xunit.visualstudio.runner v2.4.1 to v2.4.2, the test project no longer builds, giving error message:

> `1>CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point`

The project in question is an SDK project targeting `netcoreapp3.1`. It does not contain its own `Main` entrypoint. Apparently, xunit.visualstudio.runner v2.4.1 provides one.

**Comment by evolvedlight** [comment]
I get a similar but different issue, username and path snipped:

`
C:\Users\username\service.Test (nukeeper-update-xunit.runner.visualstudio-to-2.4.2 -> origin)
λ dotnet test
Test run for C:\Users\username\service.Test\bin\Debug\netcoreapp3.1\service.Test.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Unable to find C:\Users\username\service.Test\bin\Debug\netcoreapp3.1\testhost.dll. Please publish your test project and retry.

Test Run Aborted.
`
The only change from working to not working us going from 2.4.1 to 2.4.2

**Comment by matteo-mosca** [comment]
This. I have the exact same problem. Downgrading back to 2.4.1 tests start running again. With 2.4.2 I get the following message in the command line:

Unable to find C:\myproject\bin\Debug\netcoreapp3.1\testhost.dll. Please publish your test project and retry.

**Comment by buzhidao77** [comment]
I am facing the same issue saying unable to find testhost.dll after updating to 2.4.2.
Is this a known issue?

**Comment by logiclrd** [comment]
I'm pretty sure you are both having a separate issue. If you read the issue title closely you'll see that my issue is that I can't even _build_ the project.

**Comment by matteo-mosca** [comment]
You're right but I'm pretty sure those two issues might be related. Works perfectly in 2.4.1 and 2.4.2 that, by semantic versioning, should be only a bugfix breaks test projects in different ways.

**Comment by aliabdoli** [comment]
I had the same problem in .net core 3.1 test app. So, I just installed **"Microsoft.NET.Test.Sdk"** When I got the error and it fixed my problem. Not sure if it is hacking or it is meant to be like this.

My test csproj (unrelated parts removed)

```csharp 
<Project Sdk="Microsoft.NET.Sdk"> 
    <PropertyGroup>
         <TargetFramework>netcoreapp3.1</TargetFramework>
     </PropertyGroup>
     <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="3.1.4" />
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />

     <PackageReference Include="xunit" Version="2.4.1" />
     <PackageReference Include="xunit.runner.console" Version="2.4.1">
   <PackageReference Include="xunit.runner.visualstudio" Version="2.4.2">
</Project>
```

**Comment by logiclrd** [comment]
I wanted to see exactly what was different in this package from version to version, and discovered that it got moved from one repo to another, and in the original repo it lives alongside a whole bunch of other code. So I made a little script to pull every tag in from each repo and commit just `xunit.runner.visualstudio` into one place.

https://github.com/logiclrd/xunit.runner.visualstudio.releases/commits/master

Looks like there's actually rather a lot of change between 2.4.1 and 2.4.2. I don't see any super obvious way in which 2.4.1 provided a `Main` method and 2.4.2 doesn't, but it must be hiding in there somewhere.

**Comment by matteo-mosca** [comment]
If there's indeed a lot of change it's highly wrong and misleading versioning it as a bugfix. It should have been at least versioned as a minor, maybe even a major.

**Comment by logiclrd** [comment]
It looks like the code was split off from the main xUnit repository way back in 2018, and then has had incremental changes since then without any releases until just now. Basically, the 2.4.1 release precedes _every commit_ in the repository currently listed for the NuGet package:

https://github.com/xunit/visualstudio.xunit/commits/master

I agree that the version released as 2.4.2 does not appear to be an incremental bump to 2.4.1. This is conjecture, but it seems not impossible that the release of the 2.4.2 NuGet package might have been unintentional. Versioning is a tricky beast, because it seems desirable for this package to stay in lockstep with the main xUnit as a signal of compatibility. Splitting it off into a separate repository would seem to be at odds with that, though...

**Comment by eatfrog** [comment]
Got the same issue. Agree that this should not have been released to nuget like this.

**Comment by clairernovotny** [comment]
Closing as the latest test sdk reference is the fix.
